services:
  postgres:
    image: postgres:16
    container_name: nestium-postgres
    hostname: 127.0.0.1
    environment:
      POSTGRES_USER: nestium
      POSTGRES_PASSWORD: nestium
      POSTGRES_DB: nestium
    ports:
      - "5432:5432"
    volumes:
      - nestium_pg:/var/lib/postgresql/data

volumes:
  nestium_pg:
